vim.o.mouse = "a"
vim.o.completeopt = "menuone,noselect"
vim.o.wildignore = vim.o.wildignore .. "*.orig"
vim.o.wildignore = vim.o.wildignore .. "*.sw?"
vim.o.wildignore = vim.o.wildignore .. "*.DS_Store"
vim.o.wildignore = vim.o.wildignore .. "*.git"
vim.o.wildignore = vim.o.wildignore .. "*.hg"
vim.o.shortmess = vim.o.shortmess .. "c"
vim.o.colorcolumn = "81,121"
vim.o.background = "dark"
vim.cmd("syntax enable")
vim.cmd("colorscheme tokyonight")
vim.o.tabstop = 2
vim.o.shiftwidth = 2
vim.o.inccommand = "split"
vim.o.visualbell = false
vim.o.showmatch = true
vim.o.autochdir = false
vim.o.errorbells = false
vim.o.expandtab = true
vim.o.undofile = true
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.spelllang = "en"
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.termguicolors = true
vim.o.showmode = false
vim.o.hidden = true
vim.o.swapfile = false
vim.o.updatetime = 300
vim.o.timeoutlen = 500
vim.o.clipboard = "unnamed"
vim.o.guifont = "Hasklug Nerd Font Mono"
vim.wo.wrap = false
vim.wo.number = true
vim.wo.relativenumber = true
vim.wo.signcolumn = "yes"

vim.g.mapleader = "\\"
vim.g.LoupeClearHighlightMap = 0
vim.g.camelcasemotion_key = ','
