#!/usr/bin/env sh

yabai -m config status_bar                   off

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                off
yabai -m config window_border                off

yabai -m config window_opacity               on
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.7
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  54
yabai -m config bottom_padding               20
yabai -m config left_padding                 20
yabai -m config right_padding                20
yabai -m config window_gap                   10

yabai -m config mouse_modifier fn
yabai -m config focus_follows_mouse autoraise
yabai -m config mouse_follows_focus on

yabai -m config window_topmost on
yabai -m config window_shadow float

yabai -m rule --add app="^System Preferences$" manage=off border=off
yabai -m rule --add app=Preview manage=off border=off

echo "yabai configuration loaded.."
