#!/usr/bin/env sh

yabai -m config status_bar                   off

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                off
yabai -m config window_border                off

yabai -m config window_opacity               on
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.8
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  44
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   5

yabai -m config mouse_modifier fn
yabai -m config focus_follows_mouse autoraise
yabai -m config mouse_follows_focus on

yabai -m config window_topmost on
yabai -m config window_shadow float

# Space labels
yabai -m space 1 --label "🌈 Primary"
yabai -m space 2 --label "💬 Comms"
yabai -m space 3 --label "🧰 Tools"
yabai -m space 4 --label "🎧 Media"
yabai -m space 5 --label "🦄 Social"
yabai -m space 6 --label "🎈 Float"
yabai -m space 7 --label Secondary

# Space config
yabai -m config --space 6 layout float

# Unmanaged
yabai -m rule --add app="^System Preferences$" manage=off border=off
yabai -m rule --add app="Preview" manage=off border=off
yabai -m rule --add app="Harvest" manage=off border=off

# Primary
yabai -m rule --add app="Brave Browser" space=^1
yabai -m rule --add app="kitty" space=^1

# Communication
yabai -m rule --add app="Slack" space=^2
yabai -m rule --add app="Notability" space=^2
yabai -m rule --add app="Microsoft Outlook" space=^2
yabai -m rule --add app="Messages" space=^2

# Tools
yabai -m rule --add app="Finder" space=^3
yabai -m rule --add app="Microsoft Word" space=^3
yabai -m rule --add app="Sequel Pro" space=^3
yabai -m rule --add app="Postman" space=^3
yabai -m rule --add app="Sourcetree" space=^3
yabai -m rule --add app="Activity Monitor" space=^3

# Media
yabai -m rule --add app="Music" space=^4
yabai -m rule --add app="QuickTime Player" space=^4
yabai -m rule --add app="VLC" space=^4

# Social
yabai -m rule --add app="Discord" space=^5
yabai -m rule --add app="WhatsApp" space=^5

# Floating
yabai -m rule --add app="^System Preferences$" space=6

# Signals
yabai -m signal --add event=space_changed action="~/.dotfiles/scripts/ubersicht-refresh-left"
yabai -m signal --add event=display_changed action="~/.dotfiles/scripts/ubersicht-refresh-left"

echo "yabai configuration loaded.."
