#!/bin/bash

exit_script() {
    if [[ -e /tmp/dockerwait.lock ]]; then
        echo "Removing lock via trap"
        rm /tmp/dockerwait.lock
    fi
    trap - SIGINT SIGTERM # clear the trap
    kill -- -$$
}

# Wait until another process has released the lock
while [[ -e /tmp/dockerwait.lock ]]; do
    echo "Waiting for dockerwait to release lock"
    sleep 1
done

# Add a lock to be respectful with concurrent dockerwait commands
echo "Obtaining lock"
touch /tmp/dockerwait.lock

# Now that we have obtained a lock we need to clean up if we are SIGINT/TERM'd
trap exit_script SIGINT SIGTERM

echo "Checking if docker is running"
if (! docker stats --no-stream 2> /dev/null ); then
    echo "Starting Docker.app"
    open /Applications/Docker.app

    while (! docker stats --no-stream 2> /dev/null ); do
        echo -n "."
        sleep 1
    done
fi

# Remove the lock
echo "Removing lock"
rm /tmp/dockerwait.lock
